/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Colony Wars: Red Sun)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80021CECu
#define func_80021CEC BootEntry  /* alias */
